create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  name text not null,
  phone text not null,
  email text not null,
  course text not null,
  reason text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists registrations_email_lower_unique
  on public.registrations (lower(email));

alter table public.registrations enable row level security;

revoke all on table public.registrations from anon;
revoke all on table public.registrations from authenticated;