create table if not exists public.waiting_list (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  created_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists waiting_list_email_lower_unique
  on public.waiting_list (lower(email));

alter table public.waiting_list enable row level security;

revoke all on table public.waiting_list from anon;
revoke all on table public.waiting_list from authenticated;
